# https://www.appveyor.com/docs/lang/nodejs-iojs/
# Test against the latest version of this Node.js version
environment:
  nodejs_version: "12"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm ci

# Post-install test scripts.
test_script:
  - .\node_modules\.bin\cypress version
  - .\node_modules\.bin\cypress verify
  - npm test

# Don't actually build.
build: off
